<script setup>
import { onMounted, reactive } from "vue";
import { api, format_number } from "./shared.js";

const CATEGORY_STATS_PAGE = "User:DVRTed bot/AINB-stats.json";
const helper_url = mw.util.getUrl("User:DVRTed/AINB-helper");

const state = reactive({
  has_loaded: false,
  percent: "...",
  progress_stats: "Loading...",
  last_updated: "Last updated: ",
  items: [],
  total_pages: 0,
  active_cases: 0,
  total_todo: 0,
  total_in_progress: 0,
  total_completed: 0,
  total_unnecessary: 0,
  total_tagged: 0,
});

async function load_stats() {
  try {
    const result = await api.get({
      action: "query",
      prop: "revisions",
      titles: CATEGORY_STATS_PAGE,
      rvslots: "main",
      rvprop: "timestamp|content",
      format: "json",
      formatversion: "2",
    });
    const rev = result.query.pages[0].revisions[0];
    const {
      active_cases,
      total_todo,
      total_in_progress,
      total_completed,
      total_unnecessary,
      total_tagged = 0,
    } = JSON.parse(rev.slots.main.content);

    state.active_cases = format_number(active_cases);
    state.total_todo = format_number(total_todo);
    state.total_in_progress = format_number(total_in_progress);
    state.total_completed = format_number(total_completed);
    state.total_unnecessary = format_number(total_unnecessary);
    state.total_tagged = format_number(total_tagged);

    state.total_pages =
      total_todo +
      total_in_progress +
      total_completed +
      total_unnecessary +
      total_tagged;

    const resolved = total_completed + total_unnecessary + total_tagged;
    state.percent = `${Math.round((resolved / state.total_pages) * 100)}%`;
    state.progress_stats = `${format_number(resolved)} / ${format_number(
      state.total_pages,
    )} resolved`;

    const update_date = new Date(rev.timestamp).toLocaleString([], {
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: "numeric",
      minute: "2-digit",
      timeZone: "UTC",
      timeZoneName: "short",
    });

    state.last_updated = `Last updated: ${update_date}`;

    state.items = [
      { key: "todo", count: total_todo },
      { key: "completed", count: total_completed },
      { key: "unnecessary", count: total_unnecessary },
      { key: "ongoing", count: total_in_progress },
      { key: "tagged", count: total_tagged },
    ].filter(({ count }) => count > 0);
    state.has_loaded = true;
  } catch {
    state.progress_stats = "Could not load AINB stats";
  }
}

onMounted(load_stats);
</script>

<template>
  <div class="ainb-category-stats ainb-progress-wrap">
    <div class="ainb-progress-top">
      <span class="ainb-progress-percent">{{ state.percent }}</span>
      <div class="ainb-progress-top-text">
        <div class="ainb-progress-title">AI noticeboard cleanup</div>
        <div class="ainb-progress-stats">{{ state.progress_stats }}</div>
      </div>
    </div>
    <div class="ainb-progress-bar">
      <div
        v-for="{ key, count } in state.items"
        :key="key"
        class="ainb-seg"
        :class="`ainb-seg-${key}`"
        :style="{ width: `${(count / state.total_pages) * 100}%` }"
        :title="`${key}: ${count.toLocaleString()}`"
      ></div>
    </div>
    <div class="ainb-progress-legend">
      <span v-for="{ key, count } in state.items" :key="key"
        ><i class="ainb-dot" :class="`ainb-seg-${key}`"></i>{{ key }} ({{
          count.toLocaleString()
        }})</span
      >
    </div>
    <div class="ainb-category-mini" v-if="state.has_loaded">
      There are
      <strong>{{ state.active_cases }}</strong> active cases with
      <strong>{{ state.total_todo }}</strong> pages marked as to-do,
      <strong>{{ state.total_in_progress }}</strong> in progress,
      <strong>{{ state.total_tagged }}</strong> tagged,
      <strong>{{ state.total_completed }}</strong> done, and
      <strong>{{ state.total_unnecessary }}</strong>
      unnecessary.
    </div>
    <div class="ainb-category-meta">
      <span>{{ state.last_updated }}</span
      ><span>Generated by <a :href="helper_url">AINB-helper</a></span>
    </div>
  </div>
</template>
